### PR TITLE
Show how many points the user has after a roulette

### PR DESCRIPTION
**Pull request by joaopms**
99.9999999% of the times you want to know how many points you have after a roulette. This pull request fixes that by showing how many points you have after the roulette

### CODE REVIEW

**Comment by Nacht123** [comment]
idk, but the "user won 12 points in roulette, having a total of 52 points!" sounds a bit weird.

__having a total of 52 points!__ is there no better pronunciation for this :8ball:

**Comment by joaopms** [comment]
@Nacht123 any ideas then?

**Comment by T-Brawl** [comment]
"user won 69 points in roulette and now has 420 points" or "user won 69 points in roulette ! user now has 420 points" ?

**Comment by joaopms** [comment]
@T-Brawl I like the "user won 69 points in roulette and now has 420 points" one. @pajlada, what do you think?

**Comment by joaopms** [comment]
Another option is sending a whisper to the user with the points he has.

**Comment by pajlada** [comment]
@joaopms  "user won 69 points in roulette and now has 420 points" sounds good to me :+1:

**Comment by joaopms** [comment]
Alright, I'm going to close this PR and open a new one because I'm lazy to rebase ;-;

**Pull request closed without merging**
